import type { CardTemplate, Layer } from '../models/types';
import { generateId } from '../utils/id';

function createLayer(partial: Partial<Layer> & Pick<Layer, 'name' | 'type' | 'x' | 'y' | 'width' | 'height'>): Layer {
  return {
    id: generateId(),
    visible: true,
    locked: false,
    rotation: 0,
    opacity: 100,
    editable: false,
    fixedStyle: false,
    zIndex: 0,
    ...partial,
  };
}

const CARD_WIDTH = 750;
const CARD_HEIGHT = 1100;
const SIDE_PANEL_WIDTH = 135;
const PIC_HEIGHT = 810;
const DESC_START_Y = PIC_HEIGHT;

export const usaTemplate: CardTemplate = {
  id: 'usa-template',
  name: '美国势力卡牌',
  faction: '美',
  canvasWidth: CARD_WIDTH,
  canvasHeight: CARD_HEIGHT,
  layers: [
    createLayer({
      name: '卡片底色',
      type: 'shape',
      x: 0,
      y: 0,
      width: CARD_WIDTH,
      height: CARD_HEIGHT,
      backgroundColor: '#0a1628',
      zIndex: 0,
      locked: true,
    }),

    createLayer({
      name: '左侧面板底色',
      type: 'shape',
      x: 0,
      y: 0,
      width: SIDE_PANEL_WIDTH,
      height: CARD_HEIGHT,
      backgroundColor: '#0d3b8a',
      zIndex: 1,
      locked: true,
    }),

    createLayer({
      name: '左侧面板渐变',
      type: 'shape',
      x: 0,
      y: 0,
      width: SIDE_PANEL_WIDTH,
      height: CARD_HEIGHT,
      backgroundColor: 'linear-gradient(90deg, #0a2d6e 0%, #1565c0 40%, #1976d2 70%, #0d47a1 100%)',
      zIndex: 2,
      locked: true,
    }),

    createLayer({
      name: '面板分隔线',
      type: 'shape',
      x: SIDE_PANEL_WIDTH - 3,
      y: 0,
      width: 3,
      height: CARD_HEIGHT,
      backgroundColor: '#4fc3f7',
      zIndex: 3,
      locked: true,
    }),

    createLayer({
      name: '面板发光边',
      type: 'shape',
      x: SIDE_PANEL_WIDTH - 6,
      y: 0,
      width: 3,
      height: CARD_HEIGHT,
      backgroundColor: 'rgba(79, 195, 247, 0.3)',
      zIndex: 3,
      locked: true,
    }),

    createLayer({
      name: '势力字',
      type: 'text',
      x: 5,
      y: 5,
      width: 125,
      height: 130,
      text: '美',
      font: '"STKaiti", "KaiTi", "楷体", "STSong", serif',
      fontSize: 110,
      fontWeight: 'bold',
      color: '#81d4fa',
      align: 'center',
      vertical: false,
      editable: true,
      fixedStyle: true,
      zIndex: 10,
    }),

    createLayer({
      name: '称号',
      type: 'text',
      x: 30,
      y: 155,
      width: 75,
      height: 220,
      text: '美国国父',
      font: '"STKaiti", "KaiTi", "楷体", "STSong", serif',
      fontSize: 38,
      fontWeight: 'normal',
      color: '#ffd54f',
      align: 'center',
      vertical: true,
      lineHeight: 1.6,
      editable: true,
      fixedStyle: true,
      zIndex: 10,
    }),

    createLayer({
      name: '姓名',
      type: 'text',
      x: 22,
      y: 400,
      width: 90,
      height: 320,
      text: '华盛顿',
      font: '"STKaiti", "KaiTi", "楷体", "STSong", serif',
      fontSize: 76,
      fontWeight: 'bold',
      color: '#ffffff',
      align: 'center',
      vertical: true,
      lineHeight: 1.4,
      editable: true,
      fixedStyle: true,
      zIndex: 10,
    }),

    createLayer({
      name: '技能1按钮框',
      type: 'shape',
      x: 2,
      y: 820,
      width: 131,
      height: 58,
      backgroundColor: '#263238',
      borderWidth: 3,
      borderColor: '#4fc3f7',
      borderRadius: 8,
      zIndex: 8,
      locked: true,
    }),

    createLayer({
      name: '技能1按钮箭头',
      type: 'shape',
      x: 125,
      y: 830,
      width: 25,
      height: 38,
      backgroundColor: '#4fc3f7',
      zIndex: 9,
      locked: true,
    }),

    createLayer({
      name: '技能1名称',
      type: 'text',
      x: 8,
      y: 824,
      width: 115,
      height: 50,
      text: '制裁',
      font: '"STKaiti", "KaiTi", "楷体", serif',
      fontSize: 34,
      fontWeight: 'bold',
      color: '#ffd54f',
      align: 'center',
      vertical: false,
      editable: true,
      fixedStyle: true,
      zIndex: 10,
    }),

    createLayer({
      name: '技能2按钮框',
      type: 'shape',
      x: 2,
      y: 915,
      width: 131,
      height: 58,
      backgroundColor: '#263238',
      borderWidth: 3,
      borderColor: '#4fc3f7',
      borderRadius: 8,
      zIndex: 8,
      locked: true,
    }),

    createLayer({
      name: '技能2按钮箭头',
      type: 'shape',
      x: 125,
      y: 925,
      width: 25,
      height: 38,
      backgroundColor: '#4fc3f7',
      zIndex: 9,
      locked: true,
    }),

    createLayer({
      name: '技能2名称',
      type: 'text',
      x: 8,
      y: 919,
      width: 115,
      height: 50,
      text: '总攻',
      font: '"STKaiti", "KaiTi", "楷体", serif',
      fontSize: 34,
      fontWeight: 'bold',
      color: '#ffd54f',
      align: 'center',
      vertical: false,
      editable: true,
      fixedStyle: true,
      zIndex: 10,
    }),

    createLayer({
      name: '图片区域底色',
      type: 'shape',
      x: SIDE_PANEL_WIDTH,
      y: 0,
      width: CARD_WIDTH - SIDE_PANEL_WIDTH,
      height: PIC_HEIGHT,
      backgroundColor: '#1a1a2e',
      zIndex: 1,
      locked: true,
    }),

    createLayer({
      name: '人物图片',
      type: 'image',
      x: SIDE_PANEL_WIDTH,
      y: 0,
      width: CARD_WIDTH - SIDE_PANEL_WIDTH,
      height: PIC_HEIGHT,
      editable: true,
      zIndex: 5,
    }),

    createLayer({
      name: '图片暗角',
      type: 'shape',
      x: SIDE_PANEL_WIDTH,
      y: 0,
      width: CARD_WIDTH - SIDE_PANEL_WIDTH,
      height: PIC_HEIGHT,
      backgroundColor: 'linear-gradient(180deg, rgba(0,0,0,0.3) 0%, transparent 15%, transparent 70%, rgba(0,0,0,0.5) 100%)',
      zIndex: 6,
      locked: true,
    }),

    createLayer({
      name: '子弹1',
      type: 'shape',
      x: 185,
      y: 12,
      width: 24,
      height: 75,
      backgroundColor: 'bullet',
      zIndex: 7,
      locked: true,
    }),

    createLayer({
      name: '子弹2',
      type: 'shape',
      x: 230,
      y: 12,
      width: 24,
      height: 75,
      backgroundColor: 'bullet',
      zIndex: 7,
      locked: true,
    }),

    createLayer({
      name: '子弹3',
      type: 'shape',
      x: 275,
      y: 12,
      width: 24,
      height: 75,
      backgroundColor: 'bullet',
      zIndex: 7,
      locked: true,
    }),

    createLayer({
      name: '子弹4',
      type: 'shape',
      x: 320,
      y: 12,
      width: 24,
      height: 75,
      backgroundColor: 'bullet',
      zIndex: 7,
      locked: true,
    }),

    createLayer({
      name: '子弹5',
      type: 'shape',
      x: 365,
      y: 12,
      width: 24,
      height: 75,
      backgroundColor: 'bullet',
      zIndex: 7,
      locked: true,
    }),

    createLayer({
      name: '描述区域底色',
      type: 'shape',
      x: SIDE_PANEL_WIDTH,
      y: DESC_START_Y,
      width: CARD_WIDTH - SIDE_PANEL_WIDTH,
      height: CARD_HEIGHT - DESC_START_Y,
      backgroundColor: '#e0e0e0',
      zIndex: 1,
      locked: true,
    }),

    createLayer({
      name: '描述区域分隔线',
      type: 'shape',
      x: SIDE_PANEL_WIDTH,
      y: DESC_START_Y,
      width: CARD_WIDTH - SIDE_PANEL_WIDTH,
      height: 2,
      backgroundColor: '#4fc3f7',
      zIndex: 2,
      locked: true,
    }),

    createLayer({
      name: '技能1描述',
      type: 'text',
      x: SIDE_PANEL_WIDTH + 25,
      y: DESC_START_Y + 10,
      width: CARD_WIDTH - SIDE_PANEL_WIDTH - 40,
      height: 125,
      text: '当任何角色对你造成伤害时，伤害来源需给你一个武器牌，并且减2点血。',
      font: '"SimHei", "Heiti SC", "Microsoft YaHei", "黑体", sans-serif',
      fontSize: 30,
      fontWeight: 'normal',
      color: '#111111',
      align: 'left',
      vertical: false,
      lineHeight: 1.5,
      editable: true,
      fixedStyle: true,
      zIndex: 10,
    }),

    createLayer({
      name: '技能2描述',
      type: 'text',
      x: SIDE_PANEL_WIDTH + 25,
      y: DESC_START_Y + 140,
      width: CARD_WIDTH - SIDE_PANEL_WIDTH - 40,
      height: 130,
      text: '你可以命令所有美势力角色对任意玩家进攻，并且所有美系角色伤害+2',
      font: '"SimHei", "Heiti SC", "Microsoft YaHei", "黑体", sans-serif',
      fontSize: 30,
      fontWeight: 'normal',
      color: '#111111',
      align: 'left',
      vertical: false,
      lineHeight: 1.5,
      editable: true,
      fixedStyle: true,
      zIndex: 10,
    }),
  ],
};

export const allTemplates: CardTemplate[] = [usaTemplate];

export function createCardFromTemplate(template: CardTemplate): Omit<import('../models/types').Card, 'id' | 'createdAt' | 'updatedAt'> {
  return {
    name: template.name,
    templateId: template.id,
    canvasWidth: template.canvasWidth,
    canvasHeight: template.canvasHeight,
    layers: template.layers.map(layer => ({ ...layer, id: generateId() })),
  };
}
